language: go
go:
- 1.4
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/mitchellh/gox
- gox -build-toolchain -osarch=linux/386
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make lint
- make cover
- make all
after_script:
- goveralls -coverprofile=.profile.cov
after_success:
- tool/travis/autotag.sh
deploy:
  provider: releases
  api_key:
    secure: vmMQz+IjJ/LUa9SHAlLKyg4raSqkEBIRzqnjS1LK7ZjtcAROo6Pn0lUcC4qMZ96/VvNMdLyGndCOBXsdE2VBCY5goTI7uIW1oxbLM3qOMNQQldG1bOY34bjkiiDU15WLUsKKPEC2RdgwG1aAAsqcUDAeyRABYVBANSn9jylQnBC2b2mQMYUtVA1O9jl3Qg64Cy6MUUirE/SuKp/cnE3AakcQt54pNVsnM54bIyrbGhqThLj7p7uLJEm58oRWR7TTUSgmk/Rbj4aJSC4k5lzN9iL/Fr5AgnpEQQUg3ishE+5yqSW7f/PRqXC6ZI9p6XS7bhS8N178ImzouIsoKWltblsgUhfvE6ONyMpi1+RG+6Lp3HlpLuq0Pz/efEpcaSDg6lXDIvMBC2sA5pbPok6Yx4tJOSv8adWu9t0yGVJezYaqbN/071K9m3cM4YTQK4L39b2FxQ2ZrUhee8HZy5rDO8iqx2vgM+NXATz2L5Tjjzd4aqfIDX8R3PVImBci7se/wmamDUpOrcfSjrI2dzEQGBzBfIFIhCaCQSuEjpZqBKdcOztkn1uev7a0AAUeZ7my+uQNpAMO7/AapM7LLugmkLM06FgrHKWDPQP/T92MPyvmC04nNraetAVijVYLQnlK5+TdEMvkKHuY5afLp5mEzX+7jTSmjyaUNrbANs8bH/8=
  file:
  - "/home/travis/rpmbuild/RPMS/noarch/mackerel-check-plugins-0.0.3-1.noarch.rpm"
  - "/home/travis/gopath/src/github.com/mackerelio/go-check-plugins/packaging/mackerel-check-plugins_0.0.3-1_all.deb"
  on:
    repo: mackerelio/go-check-plugins
    all_branches: true
    tags: true
notifications:
  slack:
    secure: gsM+oW5k6hQnL16ubkj0Iu7b3kSeUUGCErwWa8AIBdfk6DUYBxfFNkJkHJ+N44YJPuk/ijaTk8fzQ0HqD9H+Fegkv/KPMnJ00QxOD4XWv4URFACuGQgC2xB4G8OBg7StHPN68KroQn1ryNNoAwiZih///PGJyxb4uU/FrpA8iLATBoGoaEv8OrGkkwIepvtuHeRzyMPAjNvNO6evI0d/+Xn0YLRLtufdznHG3UHc/FJ306QkMz5hbP4iZqyNFlj6sFlvvovsozTqgGYYqKz2QbMzvR3l7xuFWiV6qa6zegy6sWp9pBWykQMm528R3pVDSu/f775shORLS4DaSV7ZM3Gw963gIgfdmcqLi6KP8j+NqqyveUAq5C6JOaVDTKwJg+b2yL6TYYEQ4Lz7WiOLLmjj9V+9+i5oy852FfQEG/en9+jnPDuWDI0ILKTW8EqcQfCf46mtV0TiWY4if5iYAVUOl2O5Jam9LTX9YSeRA0qq9022tJ60GpIvX9vskO2SXTdAAQRRqM5dliOYblo0H3AmBQWTixH+AgcOP0nzAugIRX07Kpni9GfOL5bW3lBVJo1502DZWLdKoF1ulS/nHfWdz9TwuocX8hOko/H3yNH8Lt9DyodgXgWDwtYuHeuXxw7gTcaPX4K3wGgshnaBZXrryWH6u7UPT8hFePqsD58=
